#!/usr/bin/bash

# Fedora 30
rpm -e gpg-pubkey-c0aeda6e-5ad45327 2>/dev/null
rpm -e gpg-pubkey-1d14a795-5ad4532e 2>/dev/null
rpm -e gpg-pubkey-cfc659b9-5b6eac67 2>/dev/null

# Fedora 31
rpm -e gpg-pubkey-c481937a-5bc4662d 2>/dev/null
rpm -e gpg-pubkey-3c3359c4-5c6ae44d 2>/dev/null
rpm -e gpg-pubkey-54a86092-5bc4663b 2>/dev/null

true
