#!/usr/bin/bash

# get full list of all GPG keys:
# rpm -qa --qf '%{name}-%{version}-%{release} %{summary}\n' gpg-pubkey
# rpm -qa --qf '%{name}-%{version}-%{release} %{summary}\n' gpg-pubkey |grep '(32)' |awk '{ print $1 }' |sort |uniq

# Fedora 30
rpm -e gpg-pubkey-c0aeda6e-5ad45327 2>/dev/null
rpm -e gpg-pubkey-1d14a795-5ad4532e 2>/dev/null
rpm -e gpg-pubkey-cfc659b9-5b6eac67 2>/dev/null

# Fedora 31
rpm -e gpg-pubkey-c481937a-5bc4662d 2>/dev/null
rpm -e gpg-pubkey-3c3359c4-5c6ae44d 2>/dev/null
rpm -e gpg-pubkey-54a86092-5bc4663b 2>/dev/null

# Fedora 32
for i in gpg-pubkey-100bcd92-5ca9b382 gpg-pubkey-12c944d0-5d5156ab gpg-pubkey-6dc1be18-5ca9b41f; do
        rpm -e "$i" 2>/dev/null
done

# Fedora 33
rpm -e gpg-pubkey-9570ff31-5e3006fb 2>/dev/null
true
